### ISSUE TITLE
missing files from the video

### ISSUE THREAD

**Issue by kasparsbergs** [learncodeacademy/node-tutorials#1]
The ".sh" files that are in the video are not included in this repository. I know we are not suppose to run those files, but it would be easier to have a quick look, rather than to go trough a video again.

**Comment by willrstern** [comment]
@astronautskaspars which video(s) are missing the `.sh` files?

**Comment by kasparsbergs** [comment]
In video 13 you show how to use MYSQL with docker.
The .sh file,(Cheatsheet), with all the commands, is not in the repository.

**Comment by willrstern** [comment]
@astronautskaspars thanks!  I got them added now: https://github.com/learncodeacademy/node-tutorials/tree/master/13-mysql
